.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH IFCFG 5 "December 2005" "sysconfig" "Network configuration"
.\" ...

.SH NAME
ifcfg-wireless \- wireless LAN network interface configuration
.SH SYNOPSIS
.B /etc/sysconfig/network/ifcfg-wlan-*
.br
.B /etc/sysconfig/network/ifcfg-type-wlan

.SH GENERAL
Wireless networks need some additional configuration data compared to ethernet
ones. Therefore additional variables for ifcfg files were introduced.
All wireless LAN specific variables are described in the ifcfg template file
/etc/sysconfig/network/ifcfg.template. It is possible to configure more than
one wireless network accepted for association. To achieve this add suffix
.B _1 
to all wireless variables for the second network,
.B _2
for the this, and so on. Example:
.B WIRELESS_ESSID_1="second_net"
You can have up to ten wireless networks configured. Some wireless variables
are not applicable to a single wireless network but are global to the
interface. The description of the variable points this out.

.SH BUGS
Please report bugs at <http://www.suse.de/feedback>
.SH AUTHOR
.nf
Christian Zoz <zoz@suse.de> -- ifup script
Michal Svec <msvec@suse.cz> -- ifup script
Bjoern Jacke -- ifup script
Mads Martin Joergensen <mmj@suse.de> -- ifup manpage 
Michal Ludvig <mludvig@suse.cz> -- tunnel support
Joachim Gleissner <jg@suse.de> -- wireless support
.fi
.SH "SEE ALSO"
.BR ifup (8).
