.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH IFCFG-BONDING 5 "April 2005" "sysconfig" "Network configuration"
.\" ...

.SH NAME
ifcfg-bonding \- interface bonding configuration
.SH SYNOPSIS
.B /etc/sysconfig/network/ifcfg-bond*


.SH Bonding Interfaces
To setup a bonding interface you need a configuration file ifcfg-bond<X> with
the usual network settings. But you must add additional variables
.TP
.B BONDING_MASTER
must be set to 'yes' to identify this interface as a bonding interface
.TP
.B BONDING_SLAVE_<X>
here you specify the interface name representing the slave network interfaces.
.TP
.B BONDING_MODULE_OPTS
contains bonding options. Here you can set interface timeouts or working modes
('mode=active-backup' for backup mode). For additional information take a look
into the documentation mentioned at the bottom.
Note, that this options are not passed as parameters to the bonding kernel
module any more, but set via sysfs interface. This variable will be renamed
in the feature.

.SH Example 
Example for a bonding interface on eth0 and eth1 using the backup mode

.I ifcfg-bond0
.nf
   STARTMODE='onboot'
   BOOTPROTO='static'
   IPADDR='192.168.0.1/24'

   BONDING_MASTER='yes'
   BONDING_SLAVE_0='eth0'
   BONDING_SLAVE_1='eth1'
   BONDING_MODULE_OPTS='mode=active-backup miimon=100'
.fi

.SH Additional Information

For additional and more general information take a look into
.BR /usr/src/linux/Documentation/networking/bonding.txt.
Maybe you need to install the kernel sources to get this additional
documentation.
 
The configuration of routes for this kind of interface does not differ from
ordinary interfaces. See
.I man routes 
for details.

.SH BUGS
Please report bugs at <http://www.suse.de/feedback>
.SH AUTHOR
.nf
Christian Zoz <zoz@suse.de> -- ifup script
Wilken Gottwalt <wgottwalt@suse.de> -- ifcfg-bonding manual page 
.fi
.SH "SEE ALSO"
.BR ifcfg (5),
.BR ifup (8).
