.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH IFCFG-VLAN 5 "August 2004" "sysconfig" "Network configuration"
.\" ...

.SH NAME
ifcfg-vlan \- virtual LAN interface configuration
.SH SYNOPSIS
.B /etc/sysconfig/network/ifcfg-vlan*

.SH Virtual LANs (802.1q)
To setup a vlan interface you need a configuration file ifcfg-vlan<X> with the
usual network settings. Additionally there must be the variable
.B ETHERDEVICE 
that contains the real interface for the virtual LAN. The real interface will be
set UP automatically and doesn't need a config file. (But without a config file
YaST will consider this interface as unused. To avoid that just provide and
empty config file for it.)

Example that sets up vlan3 on top of eth0:

.I ifcfg-vlan3
.nf
   STARTMODE=onboot
   ETHERDEVICE=eth0
   IPADDR=192.168.3.27/24
.fi

The configuration of routes for this kind of interface does not differ from
ordinary interfaces. See
.I man routes 
for details.

.SH BUGS
Please report bugs at <http://www.suse.de/feedback>
.SH AUTHOR
.nf
Christian Zoz <zoz@suse.de> -- ifup script
Michal Svec <msvec@suse.cz> -- ifup script
Bjoern Jacke -- ifup script
Mads Martin Joergensen <mmj@suse.de> -- ifup manual page
Michal Ludvig <mludvig@suse.cz> -- tunnel support
.fi
.SH "SEE ALSO"
.BR ifcfg (5),
.BR ifup (8).
